### ISSUE TITLE
Markbot is not accepting the hover functionality

### ISSUE THREAD

**Issue by skhan9179** [skhan9179/exploding-robot-head#1]
Markbot is giving me this error:

**The website isn't functioning as expected: The position of the robot's left head piece doesn't change when the robot is hovered.**

However, the functionality works fine when I hover over the robot. Am I using the wrong class or method?

https://github.com/skhan9179/exploding-robot-head/blob/gh-pages/css/main.css#L57-L67

@thomasjbradley

**Comment by thomasjbradley** [comment]
The head pieces move up also—adjust their `top` position on hover.

**Comment by skhan9179** [comment]
It worked! Thanks
